name: CI
on:
  push:
    branches:
      - preveil
  pull_request:

jobs:

  test:
    name: Unit tests

    runs-on: windows-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      if: github.event_name == 'push'
      uses: actions/checkout@v2

    - name: Checkout pr's head commit
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2
      with:
        # on pull_request, we don't want to build on
        # the merged commit
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run unit tests
      run: make test

  golangci:
    name: Linter
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.40.0

          args: --config golangci.yml ./...
